spring-team14/simple-sns

- src/main/java/com/example/simplesns/config/WebConfig.java
feat(auth) 클래스 생성
- 인증/인가에 사용할 WebConfig 클래스 생성했습니다.
> feat(auth): WebConfig 클래스 생성

- src/main/java/com/example/simplesns/domain/user/entity/User.java
> feat(user): 엔티티 생성

- src/main/java/com/example/simplesns/domain/post/entity/Post.java
> feat(post): 게시글 엔티티 추가

- src/main/java/com/example/simplesns/domain/post/controller/PostController.java
- src/main/java/com/example/simplesns/domain/post/dto/PostRequestDto.java
- src/main/java/com/example/simplesns/domain/post/dto/PostResponseDto.java
- src/main/java/com/example/simplesns/domain/post/entity/Post.java
- src/main/java/com/example/simplesns/domain/post/repository/PostRepository.java
- src/main/java/com/example/simplesns/domain/post/service/PostService.java
feat: 게시글crud구현
실행시 "Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
Reason: Failed to determine a suitable driver class" 라는 오류가 떠서 postman으로 찔러보기는 못했지만 일단 커밋해놓고 오류 해결한 뒤에 찔러보고 문제있으면 코드 다시 수정 할 예정입니다.
> feat: 게시글curd구현

- .gitignore
공통 수정
* gitignore: application.properties 수정
> refactor(common): gitignore 수정

- src/main/java/com/example/simplesns/domain/friend/controller/FriendController.java
- src/main/java/com/example/simplesns/domain/friend/dto/common/PaginationResponse.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/DeleteFriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/FriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/ReqFriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/SignOffFriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/createFriendReqRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/response/FriendResponseDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/response/ReqFriendResponseDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/response/createFriendReqResponseDto.java
- src/main/java/com/example/simplesns/domain/friend/entity/Friend.java
- src/main/java/com/example/simplesns/domain/friend/entity/FriendRequest.java
- src/main/java/com/example/simplesns/domain/friend/entity/FriendStatus.java
- src/main/java/com/example/simplesns/domain/friend/entity/FriendStatusConverter.java
- src/main/java/com/example/simplesns/domain/friend/repository/FriendRepository.java
- src/main/java/com/example/simplesns/domain/friend/repository/FriendRequestRepository.java
- src/main/java/com/example/simplesns/domain/friend/service/FriendService.java
> feat(friend): 친구 요청 등록

- src/main/java/com/example/simplesns/domain/friend/entity/Friend.java
> fix(friend): BaseEntity 패키지 이동

- src/main/java/com/example/simplesns/domain/friend/entity/FriendRequest.java
fix(friend) 요청 엔티티 BaseEntity 패키지 이동
> fix(friend): 요청 엔티티 BaseEntity 이동

- src/main/java/com/example/simplesns/common/filter/LoginFilter.java
- src/main/java/com/example/simplesns/domain/user/controller/LoginController.java
- src/main/java/com/example/simplesns/domain/user/dto/request/LoginRequestDto.java
- src/main/java/com/example/simplesns/domain/user/entity/User.java
- src/main/java/com/example/simplesns/domain/user/repository/UserRepository.java
- src/main/java/com/example/simplesns/domain/user/service/UserService.java
- 로그인, 로그아웃 기능 구현
- 회원가입 및 비밀번호 확인 시 비밀번호 암호화 로직 적용
- 유저 수정 시 비밀번호 변경되지 않도록 수정
> feat(auth): 로그인, 로그아웃 기능 추가 및 비밀번호 암호화 적용

- src/main/java/com/example/simplesns/domain/post/controller/PostController.java
- src/main/java/com/example/simplesns/domain/post/dto/PostRequestDto.java
- src/main/java/com/example/simplesns/domain/post/dto/PostResponseDto.java
- src/main/java/com/example/simplesns/domain/post/entity/Post.java
- src/main/java/com/example/simplesns/domain/post/service/PostService.java
feat(post): 게시글crud및 user와의 연관관계 구현
> feat(post): 게시글 curd작성 및 user와의 연관관계구현

- src/main/java/com/example/simplesns/common/dto/PaginationResponse.java
- src/main/java/com/example/simplesns/domain/friend/controller/FriendController.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/ReqFriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/SignOffFriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/response/FriendResponseDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/response/ReqFriendResponseDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/response/createFriendReqResponseDto.java
- src/main/java/com/example/simplesns/domain/friend/entity/Friend.java
- src/main/java/com/example/simplesns/domain/friend/entity/FriendRequest.java
- src/main/java/com/example/simplesns/domain/friend/repository/FriendRepository.java
- src/main/java/com/example/simplesns/domain/friend/repository/FriendRequestRepository.java
- src/main/java/com/example/simplesns/domain/friend/service/FriendService.java
feat(friend) 친구관리 구현
- 친구 요청
- 친구 목록 조회
- 친구 요청 조회
- 친구요청 승인
> feat(friend): 친구 CRD, 친구요청 조회,승인 구현

- src/main/java/com/example/simplesns/domain/friend/entity/Friend.java
- src/main/java/com/example/simplesns/domain/friend/service/FriendService.java
fix(friend): 친구 삭제 로직 수정
- 친구 삭제 시 재요청을 위해 기존 요청 데이터 삭제
- 엔티티 삭제 오류(cascade 설정) 삭제
> fix(friend): 친구 삭제 로직 수정

- src/main/java/com/example/simplesns/common/config/SecurityConfig.java
- src/main/java/com/example/simplesns/domain/comment/dto/CommentResponseDto.java
- src/main/java/com/example/simplesns/domain/user/entity/User.java
소스 오류 수정
- passwordEncoder 수정
- User 엔티티 username 삭제
> fix(total): 오류 수정

- src/main/java/com/example/simplesns/domain/user/controller/UserController.java
- src/main/java/com/example/simplesns/domain/user/dto/request/UserPasswordUpdateRequestDto.java
- src/main/java/com/example/simplesns/domain/user/entity/User.java
- src/main/java/com/example/simplesns/domain/user/service/UserService.java
feat(user): UpdatePassword 추가했습니다.
> feat(user): UpdatePassword 추가

- src/main/java/com/example/simplesns/exception/code/ErrorCode.java
- src/main/java/com/example/simplesns/exception/custom/BaseException.java
- src/main/java/com/example/simplesns/exception/custom/UserNotFoundException.java
- src/main/java/com/example/simplesns/exception/dto/ErrorResponse.java
- src/main/java/com/example/simplesns/exception/handler/GlobalExceptionHandler.java
feat(exception): 공통 예외처리 구현
- Notion 에 공유된 공통 예외처리 `@RestControllerAdvice`, `@ExceptionHandler`
- 각 서비스의 예외처리에서 CustomException을 개발하신 후 적용바랍니다.
> feat(exception): 공통 예외처리 구현

- src/main/java/com/example/simplesns/domain/friend/controller/FriendController.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/FriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/FriendsPostRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/ReqFriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/SignOffFriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/request/createFriendReqRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/dto/response/FriendsPostResponseDto.java
- src/main/java/com/example/simplesns/domain/friend/repository/FriendPostRepository.java
- src/main/java/com/example/simplesns/domain/friend/repository/FriendRepository.java
- src/main/java/com/example/simplesns/domain/friend/repository/FriendRequestRepository.java
- src/main/java/com/example/simplesns/domain/friend/service/FriendService.java
- src/main/java/com/example/simplesns/exception/custom/UnauthorizedException.java
- src/main/java/com/example/simplesns/exception/custom/friend/FriendNotFoundException.java
- src/main/java/com/example/simplesns/exception/custom/friend/FriendRequestAlreadyExistException.java
- src/main/java/com/example/simplesns/exception/custom/friend/FriendRequestNotFoundException.java
refactor(friend): 친구관리 로직 수정
- 로그인 인증
- 공통 예외처리 적용
- 비즈니스 로직 수정
> refactor(friend): 친구관리 로직 수정 및 리펙토링

- src/main/java/com/example/simplesns/domain/user/controller/UserController.java
- src/main/java/com/example/simplesns/domain/user/dto/response/UserResponseDto.java
- src/main/java/com/example/simplesns/domain/user/entity/User.java
- src/main/java/com/example/simplesns/domain/user/repository/UserRepository.java
- src/main/java/com/example/simplesns/domain/user/service/UserService.java
> feat(user): 페이징 추가, 테이블명 수정

- src/main/java/com/example/simplesns/domain/friend/dto/request/DeleteFriendRequestDto.java
- src/main/java/com/example/simplesns/domain/friend/entity/Friend.java
- src/main/java/com/example/simplesns/domain/friend/service/FriendService.java
- src/main/java/com/example/simplesns/exception/code/ErrorCode.java
- src/main/java/com/example/simplesns/exception/custom/friend/FriendStatusNotWaitException.java
refactor(friend): 친구 관리 코드 리펙토링
- friend 엔티티 테이블명 (friends) 변경
- Enum 관련 소스 수정
> refactor(friend): 친구 관리 코드 리펙토링

- src/main/java/com/example/simplesns/exception/handler/GlobalExceptionHandler.java
fix(exception) : 공통 예외처리 소스 수정
- Exception -> 상속 관계에 따라 Exception이 선처리되어 해당 부분 삭제
> fix(exception): 공통 예외처리 소스 수정

- src/main/java/com/example/simplesns/domain/post/entity/Post.java
fix(post): deletedAt으로 수정 및 테이블명 복수형으로 변경
> fix(post): deletedAt 수정 및 테이블명 복수화

- src/main/java/com/example/simplesns/domain/user/entity/User.java
fix(user): 엔티티 @SQLRestriction 변경
> fix(user): 엔티티 @SQLRestriction 변경

- src/main/java/com/example/simplesns/domain/user/service/UserService.java
chore(user): @Transactional 수정
> chore(user): @Transactional 수정

- src/main/java/com/example/simplesns/domain/comment/controller/CommentController.java
- src/main/java/com/example/simplesns/domain/comment/dto/response/CommentResponseDto.java
- src/main/java/com/example/simplesns/domain/comment/repository/CommentLikeRepository.java
- src/main/java/com/example/simplesns/domain/comment/service/CommentLikeService.java
- src/main/java/com/example/simplesns/domain/comment/service/CommentService.java
댓글 조회 시 좋아요 개수 및 유저 좋아요 여부 응답 추가했습니다.
> feat(like): 댓글 조회 시 좋아요 개수 및 유저 좋아요 여부 응답 추가

- src/main/java/com/example/simplesns/domain/user/service/UserService.java
- src/main/java/com/example/simplesns/exception/custom/user/UserPasswordException.java
- src/main/java/com/example/simplesns/exception/custom/user/UserSaveAlreadyExistException.java
> fix(user): GlobalException 변경

- src/main/java/com/example/simplesns/domain/user/service/UserService.java
- src/main/java/com/example/simplesns/exception/code/ErrorCode.java
- src/main/java/com/example/simplesns/exception/custom/user/UserNewPasswordException.java
- src/main/java/com/example/simplesns/exception/custom/user/UserNotFoundEmailException.java
fix(user): GlobalException 추가 수정 및 ErrorCode 추가
> fix(user): GlobalException 추가 수정 및 ErrorCode 추가

- src/main/java/com/example/simplesns/domain/friend/entity/FriendRequest.java
- src/main/java/com/example/simplesns/domain/friend/service/FriendService.java
- src/main/java/com/example/simplesns/exception/code/ErrorCode.java
- src/main/java/com/example/simplesns/exception/custom/friend/FriendRequestToSelfException.java
fix(friend) 친구 관리 수정사항 적용
- 본인이 본인을 친구추가 할 수 없도록 검증
- 친구 요청 거절 후 재요청시 기존 요청 삭제 → 영속성 오류 수정
- 친구 게시글 조회 시 toAt NPE 해결
> fix(friend): 친구 관리 수정사항 적용

- src/main/java/com/example/simplesns/domain/user/controller/UserController.java
- src/main/java/com/example/simplesns/domain/user/dto/request/UserProfileRequestDto.java
- src/main/java/com/example/simplesns/domain/user/dto/request/UserSaveRequestDto.java
- src/main/java/com/example/simplesns/exception/handler/GlobalExceptionHandler.java
- 유저 수정/삭제 API 호출 시 로그인한 본인만 접근 가능하도록 변경
- request에 validation(@Valid) 적용
> feat(auth): 로그인한 유저만 유저 수정/삭제 가능하도록 변경 및 데이터 검증 추가

- src/main/java/com/example/simplesns/domain/post/service/PostLikeService.java
- 게시물 좋아요 등록 과정에서 userId 대신 postId를 조회하도록 수정
- 본인 게시글 좋아요 시도 시 SelfLikeNotAllowedException 발생하도록 인가 로직 추가
- post 좋아요 수 증가/감소 메서드 주석 처리 및 TODO 남김
> fix(like): 게시물 좋아요 등록 시 잘못된 postId 사용 수정

- src/main/java/com/example/simplesns/domain/post/dto/PagedResponseDto.java
- src/main/java/com/example/simplesns/domain/post/dto/PostResponseDto.java
- src/main/java/com/example/simplesns/domain/post/entity/Post.java
- src/main/java/com/example/simplesns/domain/post/service/PostLikeService.java
- src/main/java/com/example/simplesns/domain/post/service/PostService.java
- post 엔티티에 likeCount 필드 추가 및 조회 시 likeCount 응답하도록 수정
- 게시글 등록 시 deletedAt에 null 값 설정되도록 변경
- deletedAt 값이 있는 게시글 조회되지 않도록 처리
- @Transactional 어노테이션 import 경로 수정
> feat(post): 게시글 좋아요 수 필드 추가 및 deletedAt 활용 수정

- src/main/java/com/example/simplesns/domain/post/controller/PostController.java
- src/main/java/com/example/simplesns/domain/post/dto/PostRequestDto.java
- src/main/java/com/example/simplesns/domain/post/entity/Post.java
- src/main/java/com/example/simplesns/domain/post/service/PostService.java
- 게시글 수정 및 삭제 시 작성자 본인만 작업할 수 있도록 인가 로직 구현
- 권한 없을 경우 예외 발생 처리 적용
- Post 생성자에서 deletedAt 제거
> feat(auth): 게시글 수정 및 삭제 인가 로직 추가

- src/main/java/com/example/simplesns/common/filter/LoginFilter.java
> fix(auth): 로그인 필터 화이트리스트 로직 복구

- src/main/java/com/example/simplesns/domain/comment/service/CommentService.java
- src/main/java/com/example/simplesns/domain/friend/dto/response/FriendsPostResponseDto.java
- src/main/java/com/example/simplesns/domain/post/entity/Post.java
feat(friend): 친구 게시물 조회 좋아요수, 댓글수 추가
> feat(friend): 친구 게시물 조회 좋아요수, 댓글 수 추가

- src/main/java/com/example/simplesns/domain/user/dto/request/UserPasswordUpdateRequestDto.java
- src/main/java/com/example/simplesns/domain/user/dto/request/UserSaveRequestDto.java
> chore(user): 비밀번호 사이즈 추가
